# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolelanguage',
            name='ace_file_name',
            field=models.CharField(help_text='Name of ace editor file for syntax highlighting', max_length=255, verbose_name='Editor filename'),
        ),
        migrations.AlterField(
            model_name='consolelanguage',
            name='lang',
            field=models.CharField(help_text='Name of language', max_length=255, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='consolelanguage',
            name='lang_code',
            field=models.CharField(help_text='Code of language for Hackerrank API', max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
