# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolelanguages',
            name='ace_file_name',
            field=models.CharField(default='Not given', max_length=255),
            preserve_default=False,
        ),
    ]
