# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0002_consolelanguages_ace_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolelanguages',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
