# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0003_consolelanguages_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolelanguages',
            name='ace_file_name',
            field=models.CharField(max_length=255, verbose_name='editor filename'),
        ),
        migrations.AlterField(
            model_name='consolelanguages',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='consolelanguages',
            name='lang',
            field=models.CharField(max_length=255, unique=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='consolelanguages',
            name='lang_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='API code'),
        ),
    ]
