# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0003_savedcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcode',
            name='time_saved',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 18, 9, 41, 358000, tzinfo=utc), help_text='Time of last code backup', verbose_name='Last saved'),
        ),
    ]
