# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-03 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0004_auto_20170303_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConsoleLanguages',
            new_name='ConsoleLanguage',
        ),
    ]
