# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0004_savedcode_time_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedcode',
            name='time_saved',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Time of last code backup', verbose_name='Last saved'),
        ),
    ]
