# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeconsole', '0005_auto_20170303_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolelanguage',
            name='ace_file_name',
            field=models.CharField(max_length=255, verbose_name='Editor filename'),
        ),
        migrations.AlterField(
            model_name='consolelanguage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='consolelanguage',
            name='lang',
            field=models.CharField(max_length=255, unique=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='consolelanguage',
            name='lang_code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
