# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='profileimages/anonymous.jpg', upload_to='profileimages'),
        ),
    ]
