# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import www.models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_profile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(default='profileimages/anonymous.jpg', upload_to=www.models.get_user_avatar_name),
        ),
    ]
