# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_auto_20170322_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='Experience Points'),
        ),
    ]
